module Filters.Section (..) where

-- sections : List String
-- sections =
--     [ "I - Professional consultancies/law firms/self-employed consultants"
--     , "II - In-house lobbyists and trade/business/professional associations"
--     , "V - Organisations representing churches and religious communities"
--     , "IV - Think tanks, research and academic institutions"
--     , "III - Non-governmental organisations"
--     , "VI - Organisations representing local, regional and municipal authorities, other public or mixed entities, etc."
--     ]

subsections : List String
subsections =
    [ "All"
    , "Professional consultancies"
    , "Companies & groups"
    , "Organisations representing churches and religious communities"
    , "Self-employed consultants"
    , "Academic institutions"
    , "Trade and business associations"
    , "Non-governmental organisations, platforms and networks and similar"
    , "Law firms"
    , "Think tanks and research institutions"
    , "Trade unions and professional associations"
    , "Other organisations"
    , "Other public or mixed entities, created by law whose purpose is to act in the public interest"
    , "Other sub-national public authorities"
    , "Transnational associations and networks of public regional or other sub-national authorities"
    , "Regional structures"
    ]


countries : List String
countries =
    [ "All"
    , "Austria"
    , "Belgium"
    , "Bulgaria"
    , "Croatia"
    , "Czech Republic"
    , "Cyprus"
    , "Denmark"
    , "Estonia"
    , "Finland"
    , "France"
    , "Germany"
    , "Greece"
    , "Hungary"
    , "Ireland"
    , "Italy"
    , "Latvia"
    , "Lituania"
    , "Luxembourg"
    , "Malta"
    , "Netherlands"
    , "Poland"
    , "Portugal"
    , "Romania"
    , "Slovakia"
    , "Slovenia"
    , "Sweden"
    , "Spain"
    , "United Kingdom"

    , "Albania"
    , "Australia"
    , "Armenia"
    , "Argentina"
    , "Azerbaijan"
    , "Barbados"
    , "Bosnia-herzegovina"
    , "Bahamas"
    , "Belize"
    , "Bermuda"
    , "Brazil"
    , "Benin"
    , "Egypt"
    , "Canada"
    , "Cambodia"
    , "Chile"
    , "China"
    , "Congo, Democratic Republic Of"
    , "Cote D'ivoire"
    , "Dominican Republic"
    , "Malaysia"
    , "Japan"
    , "Korea, Republic Of"
    , "Tunisia"
    , "Norway"
    , "Hong Kong"
    , "India"
    , "United States"
    , "Macedonia, Former Yugoslav Republic Of"
    , "Israel"
    , "Moldova, Republic Of"
    , "Monaco"
    , "Mexico"
    , "Iraq"
    , "Paraguay"
    , "Iceland"
    , "Russia, Federation Of"
    , "Ukraine"
    , "Jordan"
    , "Nigeria"
    , "Pakistan"
    , "Philippines"
    , "Netherlands Antilles"
    , "Senegal"
    , "Syria, Arab Republic"
    , "Serbia"
    , "Switzerland"
    , "Singapore"
    , "South Africa"
    , "Turkey"
    , "Liechtenstein"
    , "Saint Marino"
    , "United Arab Emirates"
    , "Morocco"
    , "Lebanon"
    , "Qatar"
    , "Gibraltar"
    , "Kyrgyzstan"
    , "New Zealand"
    , "Trinidad And Tobago"
    , "Isle Of Man"
    , "Indonesia"
    , "Kenya"
    , "Ghana"
    , "Taiwan"
    , "Uganda"
    , "Venezuela"
    ]
